FROM ghcr.io/spack/manylinux2014:v2024-10-16

ARG PYTHON_VERSION
ARG GITHUB_ACTOR
ARG GITHUB_TOKEN

RUN tar -C /opt/_internal -xvf /opt/_internal/static-libs-for-embedding-only.tar.xz

WORKDIR /root
ENV PATH="/root/spack/bin/:$PATH" \
    SPACK_BACKTRACE=please \
    SPACK_COLOR=always \
    SPACK_PYTHON=/opt/python/cp311-cp311/bin/python \
    PYTHONUNBUFFERED=1

# Clone the repo and install Spack
RUN git clone https://github.com/spack/spack.git && \
    git -C spack checkout -b docker-reference 734c5db2121b01c373eed6538e452f18887e9e44

# Set externals, locate compilers
RUN spack external find -j 1 --not-buildable bison cmake
RUN spack compiler find
RUN spack config add "config:install_tree:padded_length:256"

COPY clingo/install_clingo.py /root/install_clingo.py

RUN ls /opt/python/

RUN export PY_PATH=$(printf '%s' "$PYTHON_VERSION" | \
    awk -F. '{maj=$1; min=$2; suf=(maj*10+min<=37)?"m":""; printf "cp%d%d-cp%d%d%s\n", maj, min, maj, min, suf}') \
    && SPACK_PYTHON=/opt/python/${PY_PATH}/bin/python3 spack python install_clingo.py

RUN spack buildcache push --unsigned ./binary-mirror $(spack --color=never find --hashes clingo-bootstrap)

RUN spack mirror add \
      --oci-username-variable GITHUB_ACTOR \
      --oci-password-variable GITHUB_TOKEN \
      ghcr oci://ghcr.io/spack/bootstrap-buildcache-pr50 && \
      spack buildcache push --unsigned ghcr clingo-bootstrap
