FROM quay.io/pypa/manylinux2014:2025.11.11-1

WORKDIR /root
ENV PATH="/root/spack/bin/:$PATH" \
    SPACK_BACKTRACE=please \
    SPACK_COLOR=always \
    SPACK_PYTHON=/opt/python/cp311-cp311/bin/python \
    PYTHONUNBUFFERED=1

# Clone the repo and install Spack
RUN mkdir /root/spack && \
    cd /root/spack && \
    git init . && \
    git fetch --depth=1 https://github.com/spack/spack.git 734c5db2121b01c373eed6538e452f18887e9e44:docker-reference && \
    git checkout docker-reference

# Set externals, locate compilers
RUN spack external find --not-buildable cmake
RUN spack compiler find
RUN spack config add "config:install_tree:padded_length:256"

RUN spack install patchelf "target=$(spack arch --family --target)"
RUN spack buildcache push --unsigned ./binary-mirror patchelf
