name: clingo

on:
  push:
    branches:
      - main
    tags:
      - v0.**
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: clingo-${{ github.ref }}
  cancel-in-progress: true

env:
  SPACK_COLOR: always
  SPACK_BACKTRACE: please
  PYTHONUNBUFFERED: 1

jobs:
  macos_build:
    runs-on: ${{ matrix.runner[0] }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        # runner + macOS deployment target
        runner: [["macos-14", "14"], ["macos-15", "15"], ["macos-26", "26"]]
        exclude:
        - python-version: "3.8"
          runner: ["macos-15", "15"]
        - python-version: "3.8"
          runner: ["macos-26", "26"]
        - python-version: "3.9"
          runner: ["macos-26", "26"]
    permissions:
      contents: read
      packages: write
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.runner[1] }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
          ref: 734c5db2121b01c373eed6538e452f18887e9e44
      # See https://github.com/actions/setup-python/issues/960
      - name: Workaround for broken Python versions from setup-python
        run: brew install gettext zlib
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install clingo-bootstrap
        run: |
          pip install --upgrade pip
          export PATH="$(brew --prefix bison):$PATH"
          . spack/share/spack/setup-env.sh

          spack config add "config:install_tree:padded_length:256"

          spack python clingo/install_clingo.py
          spack buildcache push --unsigned ./binary-mirror clingo-bootstrap

      - name: Push to OCI registry
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          . spack/share/spack/setup-env.sh
          spack mirror add \
                --oci-username-variable GITHUB_ACTOR \
                --oci-password-variable GITHUB_TOKEN \
                ghcr oci://ghcr.io/spack/bootstrap-buildcache-pr50
          spack buildcache push --unsigned ghcr clingo-bootstrap

      - uses: actions/upload-artifact@v5
        with:
          name: clingo_binary_mirror-${{ matrix.runner[0] }}-${{ matrix.python-version }}
          path: binary-mirror


  manylinux2014_build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        arch: ["amd64", "arm64", "ppc64le"]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        if: ${{ matrix.arch != 'amd64' }}
        with:
          platforms: linux/${{ matrix.arch }}

      - uses: docker/setup-buildx-action@v3

      - name: set base image
        run: |
          if [ '${{ matrix.python-version }}' = '3.14' ]; then
            echo "BASE_IMAGE=quay.io/pypa/manylinux2014:2025.11.11-1" >> $GITHUB_ENV
          else
            echo "BASE_IMAGE=ghcr.io/spack/manylinux2014:v2024-10-16" >> $GITHUB_ENV
          fi

      - uses: docker/build-push-action@v5
        with:
          file: ./clingo/Dockerfile.manylinux2014
          platforms: linux/${{ matrix.arch }}
          outputs: type=docker
          tags: clingo:latest
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            PYTHON_VERSION=${{ matrix.python-version }}
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_TOKEN=${{ github.token }}

      - run: |
          docker create --name clingo-c --platform linux/${{ matrix.arch }} clingo
          docker cp "clingo-c:/root/binary-mirror" binary-mirror

      - uses: actions/upload-artifact@v5
        with:
          name: clingo_binary_mirror-linux-${{ matrix.arch }}-${{ matrix.python-version }}
          path: binary-mirror

  clingo_json:
    runs-on: ubuntu-latest
    needs: [ macos_build, manylinux2014_build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
          ref: 734c5db2121b01c373eed6538e452f18887e9e44

      - uses: actions/download-artifact@v6

      - run: ./spack/bin/spack python ./generate_bootstrap_json.py clingo

      - uses: actions/upload-artifact@v5
        with:
          name: clingo_manifest
          path: clingo.json
