name: "Patchelf"

on:
  push:
    branches:
      - main
    tags:
      - v0.**
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: patchelf-${{ github.ref }}
  cancel-in-progress: true

env:
  SPACK_COLOR: always
  SPACK_BACKTRACE: please
  PYTHONUNBUFFERED: 1

jobs:
  manylinux2014_build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        arch: ["amd64", "arm64", "ppc64le"]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        if: ${{ matrix.arch != 'amd64' }}
        with:
          platforms: linux/${{ matrix.arch }}

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v5
        id: build
        with:
          file: ./patchelf/Dockerfile.manylinux2014
          platforms: linux/${{ matrix.arch }}
          tags: ghcr.io/${{ github.repository }}/patchelf-build:${{ matrix.arch }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/patchelf-build:${{ matrix.arch }}
          cache-to: type=inline
          push: true
          load: true

      - run: |
          docker create --name patchelf-c --platform linux/${{ matrix.arch }} ${{ steps.build.outputs.imageid }}
          docker cp "patchelf-c:/root/binary-mirror" binary-mirror

      - run: |
          docker run -e GH_TOKEN=$GH_TOKEN ${{ steps.build.outputs.imageid }} \
            /bin/bash -c "spack mirror add \
              --oci-username=${{ github.actor }} \
              --oci-password-variable=GH_TOKEN \
              ghcr oci://ghcr.io/spack/bootstrap-buildcache-v2.1 && \
              spack buildcache push --unsigned ghcr patchelf"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v5
        with:
          name: patchelf_binary_mirror-linux-${{ matrix.arch }}
          path: binary-mirror

  patchelf_json:
    runs-on: ubuntu-latest
    needs: [ manylinux2014_build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
          ref: 734c5db2121b01c373eed6538e452f18887e9e44
      - uses: actions/checkout@v4
        with:
          repository: spack/spack-packages
          path: spack-packages
          ref: a5b98e6b7e411a499f310e048c1d2e39d1004519
      - uses: actions/download-artifact@v6
      - uses: actions/upload-artifact/merge@v5
        with:
          name: patchelf_combined
          pattern: patchelf_binary_mirror-*
          delete-merged: true
      - run: |
          . spack/share/spack/setup-env.sh
          spack repo set --destination "$PWD/spack-packages" builtin
          spack python ./generate_bootstrap_json.py patchelf
      - uses: actions/upload-artifact@v5
        with:
          name: patchelf_manifest
          path: patchelf.json
